apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: 060425629624.dkr.ecr.ap-south-1.amazonaws.com/vrs-fe:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always

