apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: 060425629624.dkr.ecr.ap-south-1.amazonaws.com/vrs-be:latest
        ports:
        - containerPort: 5050
        env: 
        - name: VRS_USER
          value: <DB_USER>
        - name: VRS_PASS
          value: <DB_PASS>
        - name: VRS_DB_URL
          value: jdbc:postgresql://postgres:5432/<DB_NAME>
        - name: VRS_MAIL_USERNAME
          value: <SMTP_USERNAME>
        - name: VRS_MAIL_PASSWORD
          value: <SMTP_PASSWORD>
        imagePullPolicy: Always
